### ISSUE TITLE
has_required_permisions typo or bypass of naming conflict?

### ISSUE THREAD

**Issue by rsommerard** [identixone/fastapi_contrib#156]
* FastAPI Contrib version: 0.2.8
* FastAPI version: 0.61.1
* Python version: 3.8
* Operating System: Ubuntu 20.04

`has_required_permisions` method from `BasePermission` class should be `has_required_permissions`, is it a typo or is it a trick to bypass a naming conflict?

**Comment by levchik** [comment]
Hi @rsommerard , I guess it is actually a typo! Thanks for noticing, would you mind making a PR?

**Comment by rsommerard** [comment]
Yep, I will do the change and provide a PR.

**Comment by levchik** [comment]
Closed by #157
