### ISSUE TITLE
Importing models as a package and creating indexes

### ISSUE THREAD

**Issue by mumtozvalijonov** [identixone/fastapi_contrib#159]
* FastAPI Contrib version: 0.2.8
* FastAPI version: 0.60.1
* Python version: 3.7.3
* Operating System: MacOS

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

As some of my model classes are big enough (~50-100) lines I wanted to divide models into files, one file for each MongoDBModel. The case is that these new models are not listed while create_index() is called, I even debugged the sources and it seems like **fastapi_contrib** cannot find those model classes anymore. Creating an __init__.py and importing those models there did not help as well.

### What I Did

Investigation shows that the **fastapi_contrib.db.utils.get_models()** is searching for a signle *.py file to contain all the models. What could be better is, in my opinion to alter a code a bit, so that the function **get_models** will look like the following:

```
    from fastapi_contrib.db.models import MongoDBModel
    import inspect

    apps_folder_name = settings.apps_folder_name
    models = []
    for app in settings.apps:
        app_path = f"{apps_folder_name}/{app}"
        modules = [f for f in pkgutil.walk_packages(path=[app_path]) if f.name == 'models']
        if not modules:
            continue
        for module in modules:
            path_to_models = f"{apps_folder_name}.{app}.models"
            mudule = importlib.import_module(path_to_models)
            if module.ispkg:
                module_models = [x[0] for x in inspect.getmembers(mudule, inspect.isclass)]
            else:
                try:
                    module_models = pyclbr.readmodule(path_to_models).keys()
                except (AttributeError, ImportError):
                    logger.warning(
                        f"Unable to read module attributes in {path_to_models}"
                    )
                    continue
            models.extend([getattr(mudule, model) for model in module_models])

```

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by levchik** [comment]
Hi @mumtozvalijonov, thanks for the PR! LGTM, I think that this might be quite useful for some users of this lib. Yeah, so I'm gonna merge it. I'm planning on releasing new version to pypi later this week. 

Thank you 🙇

Closed by #160
