### ISSUE TITLE
Allow overriding settings from fastAPI app

### ISSUE THREAD

**Issue by pheanex** [identixone/fastapi_contrib#166]
* FastAPI Contrib version: 0.2.9
* FastAPI version: 0.52.0
* Python version: 3.8.2
* Operating System: Linux

### Description

Currently we can only override settings with settings from the fastAPI app by using environment variables (See the [Todo](https://github.com/identixone/fastapi_contrib/blob/081670603917b1b7e9646c75fba5614b09823a3e/fastapi_contrib/conf.py#L72)).
Can we implement this functionaility, so we do not have to go through the environment variables?

**Comment by levchik** [comment]
Hi @pheanex, 

I didn't try myself, but I think mutating settings object directly solves your use-case:

```python
from fastapi_contrib.conf import settings

settings. log_level = "DEBUG"
```

If you do it right at the start of your app, I guess these changed settings should apply globally and work as expected.

And yeah, if this doesn't work and you have an idea on how to do it properly, you are very welcome to suggest.

**Comment by levchik** [comment]
Ok, I'm closing this for now
