### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by pheanex** [identixone/fastapi_contrib#169]
### Description

What do you think about adding a changelog so users know what changes to expect from a version update?

**Comment by levchik** [comment]
Hi @pheanex 

Yeah, sure, I've started to write detailed change log of a release since 0.2.10

Check it out: https://github.com/identixone/fastapi_contrib/releases/tag/v0.2.10

Do you think this should be enough?

**Comment by pheanex** [comment]
That is great! :partying_face: Thank you for doing that!
I wonder if it still makes sense to add a changelog.md or something to the project or mention it in the readme that the changelog is on github releases to make it more visible.
Some also put it in the [project_urls for showing on pypi](https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls)

**Comment by levchik** [comment]
Sure, let's do this starting from next release

**Comment by levchik** [comment]
Closing this for https://github.com/identixone/fastapi_contrib/commit/e61ecaa3fc114aebb89f4ced28b75bb6dfd21f05

If you have further suggestions, please open new request :)
