### ISSUE TITLE
ModuleNotFoundError: No module named 'fastapi_contrib'

### ISSUE THREAD

**Issue by seongkyu-lim** [identixone/fastapi_contrib#184]
* FastAPI Contrib version: 0.2.11
* FastAPI version: 0.78.0
* Python version: 3.8.13
* Operating System: mac

### Description

I cloned fastapi project which uses fastapi-contrib library.

and then i installed fastapi-contrib with `$ pip install fastapi_contrib`.

but **ModuleNotFoundError: No module named 'fastapi_contrib'** was logged repeatly. 😅

Thank you for your busy schedule. 🙏🏼

### What I Did

- Pycharm turned off and on.
- `$ pip install fastapi_contrib[all]` (but it says `zsh: no matches found: fastapi_contrib[all]`)

**Comment by thanhnt7392** [comment]
@seongkyu-lim I think u can try `pip install fastapi-contrib[all]` not Underlined '_'

**Comment by seongkyu-lim** [comment]
[thanhnt7038](https://github.com/thanhnt7038) thank you! have a good day :)
