### ISSUE TITLE
Add Support for FastAPI latest version

### ISSUE THREAD

**Issue by vveliev-tc** [identixone/fastapi_contrib#66]
* FastAPI Contrib version:
* FastAPI version: 0.45.0
* Python version: 3.7
* Operating System: Linux

### Description

 pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches fastapi==0.42.0,==0.45.0

### What I Did

```
Trying to use lib with FastAPI 0.45.0 and up
```

**Comment by levchik** [comment]
Hi, to see why latest supported version of FastAPI is 0.42.0 for now, look at this comment https://github.com/identixone/fastapi_contrib/issues/34#issuecomment-546464931

There are plans (see Project tasks) to have that covered, but I'm afraid I'm not gonna have time for that any soon, at least not in the next month or so.

If you're willing to make pull request though, I would gladly code review that.

**Comment by levchik** [comment]
Support for the latest (for now) FastAPI & Pydantic version is out now in v0.2.4
